version: "3"
services:
  nginx:
    depends_on:
      - wordpress
    # build:
      # context: ./nginx
    container_name: "inception_nginx"
    image: ft_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/data/wp_nginx:/var/www/wordpress
    restart: always

####################### wordpress #########################
  wordpress:
    depends_on:
      - mariadb
    # build:
      # context: ./wordpress
    image: ft_wordpress
    container_name: "inception_wordpress"
    env_file:
      - "/root/.env"
    volumes:
      - /tmp/data/wp_nginx:/var/www/wordpress
    restart: always

####################### mariadb #########################

  mariadb:
    # build:
      # context: ./mariadb
    container_name: "inception_mariadb"
    image: ft_mariadb
    env_file:
      - "/root/.env" #inclusion du  fichier .env :)
    volumes:
      - /tmp/data/database:/var/lib/mysql
    restart: always