---
- name: copy files to destination
  hosts: all
  # become: yes  # If superuser (sudo) privileges are required
  # tasks:
  #   - name: Install docker
  #     include_role:
  #       name: docker

  roles:
    - docker
    - nginx_role
    - wordpress_role
    - db_role

  become: yes  # If superuser (sudo) privileges are required
  tasks:
    - name: Send env
      copy:
        src: .env
        dest: .env
      
    - name: Send compose
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml

    - name: down compose down and delete volume 
      ansible.builtin.command:
        cmd: docker-compose down -v

    - name: Start compose up
      ansible.builtin.command:
        cmd: docker-compose up -d