---
# Install Docker
# --
#
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes
    state: present

- name: add apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

# - name: add userpermissions
#   shell: "usermod -aG docker {{ REMOTE_USER }}"

# Installs Docker SDK
# --
#
- name: install python package manager
  apt:
    name: python3-pip
    state: present

- name: install python sdk
  # become_user: "{{ REMOTE_USER }}"
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: docker prune
  ansible.builtin.command:
    cmd: docker system prune -f