---
- name: copy image nginx  to remotely server 
  copy:
    src: images/nginx
    dest: /tmp/images

- name: Build ft_nginx
  ansible.builtin.command:
    cmd: docker build -t ft_nginx  /tmp/images/nginx/
